<a href="https://colab.research.google.com/github/leadeev/Numpy/blob/main/03_Numpy_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Execute the cell below before starting the 1st mission.

In [ ]:
array_1 = np.array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

array_1

array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

# Mission 1

Using Numpy, how many axes `array_1` have ?




In [ ]:
array_1.shape

(32,)

Réponse: Il y a un axe, qui contient 32 éléments.

How many dimensions `array_1` have?

In [ ]:
array_1.ndim

1

Accesses the first element of `array_1`

In [ ]:
array_1[0]

10

# Mission 2

Modify, using a `numpy` method, the `array_1` object to be an object that has two axes, including 1 row and 32 columns.  
Save it under the variable `array_2`.

In [ ]:
array_2 = array_1.reshape(1,32)

array_2

array([[10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54,
        54, 35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35]])

Now, modify `array_1` into an object that has 32 rows and only 1 column.  
Save it under the variable `array_3`.

In [ ]:
array_3 = array_1.reshape(32,1)
array_3

array([[10],
       [40],
       [45],
       [ 5],
       [66],
       [91],
       [43],
       [75],
       [40],
       [28],
       [55],
       [45],
       [31],
       [71],
       [67],
       [54],
       [54],
       [35],
       [64],
       [27],
       [12],
       [93],
       [17],
       [91],
       [50],
       [57],
       [74],
       [61],
       [86],
       [20],
       [36],
       [35]])

Accesses the first value of `array_2`, then of `array_3`.  
What do you notice?  
Why ?

The first value of array_2 is a list that contains 32 elements.
The first value of array_3 is a list that contains 1 element.
This is because a row requires a new list to be created each time, while for a column the items follow one another next to each other in the same list.



In [ ]:
array_2[0]

array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

In [ ]:
array_3[0]

array([10])

# Mission 3

Accesses the value that is at index 3 of array `array_2`.  
Do it with Numpy way, then with Python way.

In [ ]:
# Numpy way

array_2[0,3]


5

In [ ]:
# Python way

list(array_2)[0][3]

5

Accesses the value which is at index 3 of array `array_3` in Numpy.

In [ ]:
# Numpy way


print(array_3[3][0])
array_3[:,0][3]

5


5

# Mission 4

Reshape `array_1` to be a 4-row, 8-column array,
rather than a 32-element vector.  
Save your array under the variable `array_4`.

In [ ]:
array_1

array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

In [ ]:
array_4 = array_1.reshape(4,8)

array_4

array([[10, 40, 45,  5, 66, 91, 43, 75],
       [40, 28, 55, 45, 31, 71, 67, 54],
       [54, 35, 64, 27, 12, 93, 17, 91],
       [50, 57, 74, 61, 86, 20, 36, 35]])

Accesses for each row, the values ​​of the columns which have the index 1 to 2 included.

In [ ]:
array_4[:, 1:3] 

array([[40, 45],
       [28, 55],
       [35, 64],
       [57, 74]])


Accesses for rows at position 1 and 2 inclusive, the values ​​of all columns.

In [ ]:
array_4[0:2,:]

array([[10, 40, 45,  5, 66, 91, 43, 75],
       [40, 28, 55, 45, 31, 71, 67, 54]])

Accesses for the rows which have the index 2 to 3 inclusive, to the values ​​of the columns which have the index 3 to 5 inclusive.

In [ ]:
array_4[2:4, 3:6]

array([[27, 12, 93],
       [61, 86, 20]])

Selects the first column, as well as the columns whose index is a multiple of 2.

In [ ]:
array_4[:,::2]

array([[10, 45, 66, 43],
       [40, 55, 31, 67],
       [54, 64, 12, 17],
       [50, 74, 86, 36]])

Select columns whose index is odd.

In [ ]:
array_4[:,1::2]

array([[40,  5, 91, 75],
       [28, 45, 71, 54],
       [35, 27, 93, 91],
       [57, 61, 20, 35]])

# Mission 5

Reshape your `array_1` vector into a 3-dimensional array.
Your 3-dimensional array should have 2 matrices, each of which has 4 rows and 4 columns.
Save your array under the variable `array_5`.

In [ ]:
array_5 = array_1.reshape(2,4,4)

array_5

array([[[10, 40, 45,  5],
        [66, 91, 43, 75],
        [40, 28, 55, 45],
        [31, 71, 67, 54]],

       [[54, 35, 64, 27],
        [12, 93, 17, 91],
        [50, 57, 74, 61],
        [86, 20, 36, 35]]])

Use the .shape attribute to observe the number of axes for `array_5`.

In [ ]:
array_5.shape

(2, 4, 4)

Selects all values ​​from the first matrix.

In [ ]:
array_5[0,:,:]

array([[10, 40, 45,  5],
       [66, 91, 43, 75],
       [40, 28, 55, 45],
       [31, 71, 67, 54]])

Accesses for both matrices,
to the values ​​corresponding to the rows at index 1 and to the columns that have positions 3 and 4.

In [ ]:
array_5[:,1,2:]

array([[43, 75],
       [17, 91]])

Accesses row values ​​at positions 2 through 3,
columns at indexes 1 to 3 for the second matrix only.

In [ ]:
array_5[1,1:3,1:]

array([[93, 17, 91],
       [57, 74, 61]])


Reshape `array_5` so that we have 8 rows and 4 columns.

In [ ]:
array_5.reshape(8,4)

array([[10, 40, 45,  5],
       [66, 91, 43, 75],
       [40, 28, 55, 45],
       [31, 71, 67, 54],
       [54, 35, 64, 27],
       [12, 93, 17, 91],
       [50, 57, 74, 61],
       [86, 20, 36, 35]])